# Generated by Django 4.1.2 on 2022-10-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="To'lov turi nomi")),
            ],
            options={
                'verbose_name': "To'lov turi",
                'verbose_name_plural': "To'lov turlari",
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Rang nomi')),
                ('color', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Mahsulot rangi',
                'verbose_name_plural': 'Mahsulot ranglari',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="O'lcham")),
            ],
            options={
                'verbose_name': "Mahsulot o'lchami",
                'verbose_name_plural': "Mahsulot o'lchamlari",
            },
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Davlat nomi')),
            ],
            options={
                'verbose_name': 'Mahsulot ishlab chiqarilgan davlat',
                'verbose_name_plural': 'Mahsulot ishlab chiqarilgan davlatlar',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ijtimoiy tarmoq nomi')),
                ('url', models.URLField(verbose_name='Ijtimoiy tarmoq manzili(url)')),
                ('icon', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 3')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/video/%Y/%m/%d', verbose_name='Video fayl')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('discount', models.PositiveSmallIntegerField(null=True, verbose_name='Chegirma')),
                ('content', models.TextField(null=True, verbose_name='Qisqacha tovar haqida')),
                ('slug', models.SlugField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('colors', models.ManyToManyField(to='shop.productcolor', verbose_name='Ranglar')),
                ('sizes', models.ManyToManyField(to='shop.productsize', verbose_name="O'lchamlar")),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productstate', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Buyurtmachi ismi')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Buyurtmachi telefon raqami')),
                ('address', models.CharField(max_length=200, verbose_name='Buyurtmachi manzili')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Buyurtma yetkazildi')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Buyurtma bekor qilindi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor', verbose_name='Mahsulot rangi')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.paymenttype', verbose_name="Buyurtma to'lov turi")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Mahsulot')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name="Mahsulot O'lchami")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
