# Generated by Django 4.1.2 on 2022-10-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/video/%Y/%m/%d')),
                ('iframe', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('colors', models.ManyToManyField(to='shop.productcolor')),
                ('sizes', models.ManyToManyField(to='shop.productsize')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productstate')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.paymenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize')),
            ],
        ),
    ]
