# Generated by Django 4.1.2 on 2022-10-18 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': "To'lov turi", 'verbose_name_plural': "To'lov turlari"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Mahsulot rangi', 'verbose_name_plural': 'Mahsulot ranglari'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': "Mahsulot o'lchami", 'verbose_name_plural': "Mahsulot o'lchamlari"},
        ),
        migrations.AlterModelOptions(
            name='productstate',
            options={'verbose_name': 'Mahsulot ishlab chiqarilgan davlat', 'verbose_name_plural': 'Mahsulot ishlab chiqarilgan davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Ijtimoiy tarmoq', 'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
        migrations.AddField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Buyurtma bekor qilindi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Buyurtma yetkazildi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Buyurtmachi manzili'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor', verbose_name='Mahsulot rangi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='Buyurtmachi ismi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.paymenttype', verbose_name="Buyurtma to'lov turi"),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Buyurtmachi telefon raqami'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize', verbose_name="Mahsulot O'lchami"),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=250, verbose_name="To'lov turi nomi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='shop.productcolor', verbose_name='Ranglar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqacha tovar haqida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iframe',
            field=models.TextField(blank=True, null=True, verbose_name='YouTube video manzil'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Rasm 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='shop.productsize', verbose_name="O'lchamlar"),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productstate', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/video/%Y/%m/%d', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Rang nomi'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=250, verbose_name="O'lcham"),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Davlat nomi'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Ijtimoiy tarmoq nomi'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='Ijtimoiy tarmoq manzili(url)'),
        ),
    ]
