# Generated by Django 4.1.2 on 2022-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orders_options_alter_paymenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
